//! Differential tests comparing the BPF programs generated by libseccomp and
//! by this module.

use std::collections::HashSet;
use std::io::{Read, Seek};
use std::path::PathBuf;

use oci_spec::runtime::{
    Arch, LinuxSeccomp, LinuxSeccompAction, LinuxSeccompArgBuilder, LinuxSeccompBuilder,
    LinuxSeccompOperator, LinuxSyscallBuilder,
};
use youki_seccomp::instruction::{AUDIT_ARCH_X86_64, Instruction, X32_SYSCALL_BIT};

use super::compiler::interp::{Data, run};
use super::compiler::{self, Rule};
use super::{ScmpAction, ScmpArch, ScmpArgCompare, ScmpCompareOp, ScmpSyscall};

fn action(action: LinuxSeccompAction, errno: Option<u32>) -> ScmpAction {
    let errno = errno.map(|e| e as i32).unwrap_or(libc::EPERM);
    match action {
        LinuxSeccompAction::ScmpActKill => ScmpAction::KillThread,
        LinuxSeccompAction::ScmpActTrap => ScmpAction::Trap,
        LinuxSeccompAction::ScmpActErrno => ScmpAction::Errno(errno),
        LinuxSeccompAction::ScmpActTrace => ScmpAction::Trace(errno as u16),
        LinuxSeccompAction::ScmpActAllow => ScmpAction::Allow,
        LinuxSeccompAction::ScmpActKillProcess => ScmpAction::KillProcess,
        LinuxSeccompAction::ScmpActNotify => ScmpAction::Notify,
        LinuxSeccompAction::ScmpActLog => ScmpAction::Log,
        LinuxSeccompAction::ScmpActKillThread => ScmpAction::KillThread,
    }
}

fn to_libseccomp_action(action: ScmpAction) -> libseccomp::ScmpAction {
    match action {
        ScmpAction::KillProcess => libseccomp::ScmpAction::KillProcess,
        ScmpAction::KillThread => libseccomp::ScmpAction::KillThread,
        ScmpAction::Trap => libseccomp::ScmpAction::Trap,
        ScmpAction::Notify => libseccomp::ScmpAction::Notify,
        ScmpAction::Errno(e) => libseccomp::ScmpAction::Errno(e),
        ScmpAction::Trace(t) => libseccomp::ScmpAction::Trace(t),
        ScmpAction::Log => libseccomp::ScmpAction::Log,
        ScmpAction::Allow => libseccomp::ScmpAction::Allow,
    }
}

fn op(op: LinuxSeccompOperator, value_two: Option<u64>) -> ScmpCompareOp {
    match op {
        LinuxSeccompOperator::ScmpCmpNe => ScmpCompareOp::NotEqual,
        LinuxSeccompOperator::ScmpCmpLt => ScmpCompareOp::Less,
        LinuxSeccompOperator::ScmpCmpLe => ScmpCompareOp::LessOrEqual,
        LinuxSeccompOperator::ScmpCmpEq => ScmpCompareOp::Equal,
        LinuxSeccompOperator::ScmpCmpGe => ScmpCompareOp::GreaterEqual,
        LinuxSeccompOperator::ScmpCmpGt => ScmpCompareOp::Greater,
        LinuxSeccompOperator::ScmpCmpMaskedEq => ScmpCompareOp::MaskedEqual(value_two.unwrap_or(0)),
    }
}

fn to_libseccomp_cmp(cmp: &ScmpArgCompare) -> libseccomp::ScmpArgCompare {
    let op = match cmp.op {
        ScmpCompareOp::NotEqual => libseccomp::ScmpCompareOp::NotEqual,
        ScmpCompareOp::Less => libseccomp::ScmpCompareOp::Less,
        ScmpCompareOp::LessOrEqual => libseccomp::ScmpCompareOp::LessOrEqual,
        ScmpCompareOp::Equal => libseccomp::ScmpCompareOp::Equal,
        ScmpCompareOp::GreaterEqual => libseccomp::ScmpCompareOp::GreaterEqual,
        ScmpCompareOp::Greater => libseccomp::ScmpCompareOp::Greater,
        ScmpCompareOp::MaskedEqual(m) => libseccomp::ScmpCompareOp::MaskedEqual(m),
    };
    libseccomp::ScmpArgCompare::new(cmp.arg, op, cmp.datum)
}

fn to_libseccomp_arch(arch: ScmpArch) -> libseccomp::ScmpArch {
    match arch {
        ScmpArch::X8664 => libseccomp::ScmpArch::X8664,
        ScmpArch::X86 => libseccomp::ScmpArch::X86,
        ScmpArch::X32 => libseccomp::ScmpArch::X32,
        ScmpArch::Aarch64 => libseccomp::ScmpArch::Aarch64,
        ScmpArch::Arm => libseccomp::ScmpArch::Arm,
        arch => panic!("unsupported arch {arch:?}"),
    }
}

fn to_arch(arch: Arch) -> ScmpArch {
    match arch {
        Arch::ScmpArchNative => ScmpArch::Native,
        Arch::ScmpArchX86 => ScmpArch::X86,
        Arch::ScmpArchX86_64 => ScmpArch::X8664,
        Arch::ScmpArchX32 => ScmpArch::X32,
        Arch::ScmpArchAarch64 => ScmpArch::Aarch64,
        Arch::ScmpArchArm => ScmpArch::Arm,
        arch => panic!("unsupported arch {arch:?}"),
    }
}

/// Translates `seccomp` the same way as `crate::seccomp::initialize_seccomp`.
fn translate(seccomp: &LinuxSeccomp) -> (ScmpAction, Vec<ScmpArch>, Vec<Rule>) {
    let default = action(seccomp.default_action(), seccomp.default_errno_ret());
    let mut archs = vec![ScmpArch::Native.resolve_native().unwrap()];
    for &arch in seccomp.architectures().iter().flatten() {
        let arch = to_arch(arch).resolve_native().unwrap();
        if !archs.contains(&arch) {
            archs.push(arch);
        }
    }
    let mut rules = vec![];
    for syscall in seccomp.syscalls().iter().flatten() {
        let action = action(syscall.action(), syscall.errno_ret());
        if action == default {
            continue;
        }
        for name in syscall.names() {
            let Ok(sc) = ScmpSyscall::from_name(name) else {
                continue;
            };
            let comparators: Vec<ScmpArgCompare> = syscall
                .args()
                .iter()
                .flatten()
                .map(|arg| {
                    ScmpArgCompare::new(
                        arg.index() as u32,
                        op(arg.op(), arg.value_two()),
                        arg.value(),
                    )
                })
                .collect();
            let mut seen = HashSet::new();
            if comparators.iter().all(|c| seen.insert(c.arg)) {
                rules.push(Rule {
                    action,
                    syscall: sc,
                    comparators,
                });
            } else {
                for cmp in comparators {
                    rules.push(Rule {
                        action,
                        syscall: sc,
                        comparators: vec![cmp],
                    });
                }
            }
        }
    }
    (default, archs, rules)
}

/// Builds the BPF program with libseccomp.
fn libseccomp_program(default: ScmpAction, archs: &[ScmpArch], rules: &[Rule]) -> Vec<Instruction> {
    let mut ctx = libseccomp::ScmpFilterContext::new(to_libseccomp_action(default)).unwrap();
    for &arch in archs {
        ctx.add_arch(to_libseccomp_arch(arch)).unwrap();
    }
    for rule in rules {
        let sc = libseccomp::ScmpSyscall::from_name(rule.syscall.name()).unwrap();
        let cmps: Vec<_> = rule.comparators.iter().map(to_libseccomp_cmp).collect();
        ctx.add_rule_conditional(to_libseccomp_action(rule.action), sc, &cmps)
            .unwrap();
    }
    let mut file = tempfile::tempfile().unwrap();
    ctx.export_bpf(&file).unwrap();
    file.rewind().unwrap();
    let mut bytes = vec![];
    file.read_to_end(&mut bytes).unwrap();
    bytes
        .chunks_exact(8)
        .map(|b| Instruction {
            code: u16::from_ne_bytes([b[0], b[1]]),
            offset_jump_true: b[2],
            offset_jump_false: b[3],
            multiuse_field: u32::from_ne_bytes([b[4], b[5], b[6], b[7]]),
        })
        .collect()
}

/// Argument values around the data of the comparators.
fn interesting_values(rules: &[Rule]) -> Vec<u64> {
    let mut values: HashSet<u64> = [0, 1, u32::MAX as u64, u64::MAX].into();
    for cmp in rules.iter().flat_map(|r| &r.comparators) {
        for base in [cmp.datum, cmp.datum | 0xffff_0000, !cmp.datum] {
            values.extend([base.wrapping_sub(1), base, base.wrapping_add(1)]);
            values.insert(base ^ (1 << 32));
        }
    }
    values.into_iter().collect()
}

/// Asserts both programs return the same value for every syscall of the
/// native architecture and the argument values related to the rules.
fn assert_equivalent(seccomp: &LinuxSeccomp) {
    let (default, archs, rules) = translate(seccomp);
    let expected = libseccomp_program(default, &archs, &rules);
    let actual = compiler::compile(default, ScmpAction::KillThread, &archs, &rules).unwrap();

    let audit = super::arch::info(archs[0]).unwrap().audit;
    let mut nrs: Vec<u32> = (0..1024).collect();
    if audit == AUDIT_ARCH_X86_64 {
        nrs.extend((0..1024).map(|nr| nr | X32_SYSCALL_BIT));
    }
    let mut inputs: Vec<Data> = [audit, 0]
        .iter()
        .flat_map(|&arch| {
            nrs.iter().map(move |&nr| Data {
                nr,
                arch,
                args: [0; 6],
            })
        })
        .collect();
    // Vary the arguments of the syscalls with conditional rules only.
    let values = interesting_values(&rules);
    for rule in rules.iter().filter(|r| !r.comparators.is_empty()) {
        let Some(nr) = super::arch::resolve(archs[0], rule.syscall.name()) else {
            continue;
        };
        for index in 0..6 {
            for &value in &values {
                let mut args = [0x10; 6];
                args[index] = value;
                inputs.push(Data {
                    nr,
                    arch: audit,
                    args,
                });
            }
        }
    }

    for data in inputs {
        assert_eq!(
            run(&actual, &data),
            run(&expected, &data),
            "mismatch for {data:?}"
        );
    }
}

#[test]
fn test_equivalent_moby() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/seccomp/fixture/config.json");
    let spec = oci_spec::runtime::Spec::load(path).unwrap();
    let seccomp = spec.linux().as_ref().unwrap().seccomp().as_ref().unwrap();
    assert_equivalent(seccomp);
}

#[test]
fn test_equivalent_operators() {
    let ops = [
        LinuxSeccompOperator::ScmpCmpNe,
        LinuxSeccompOperator::ScmpCmpLt,
        LinuxSeccompOperator::ScmpCmpLe,
        LinuxSeccompOperator::ScmpCmpEq,
        LinuxSeccompOperator::ScmpCmpGe,
        LinuxSeccompOperator::ScmpCmpGt,
        LinuxSeccompOperator::ScmpCmpMaskedEq,
    ];
    let syscalls = ops
        .iter()
        .zip([
            "socket",
            "personality",
            "clone",
            "ioctl",
            "mmap",
            "prctl",
            "fcntl",
        ])
        .enumerate()
        .map(|(i, (&op, name))| {
            LinuxSyscallBuilder::default()
                .names(vec![name.to_string()])
                .action(LinuxSeccompAction::ScmpActErrno)
                .errno_ret(i as u32 + 1)
                .args(vec![
                    LinuxSeccompArgBuilder::default()
                        .index(i % 6)
                        .value(0x1_0000_0010u64)
                        .value_two(0xffff_0000_00f0u64)
                        .op(op)
                        .build()
                        .unwrap(),
                    LinuxSeccompArgBuilder::default()
                        .index((i + 1) % 6)
                        .value(7u64)
                        .op(LinuxSeccompOperator::ScmpCmpGe)
                        .build()
                        .unwrap(),
                ])
                .build()
                .unwrap()
        })
        .collect::<Vec<_>>();
    let seccomp = LinuxSeccompBuilder::default()
        .default_action(LinuxSeccompAction::ScmpActAllow)
        .architectures(vec![Arch::ScmpArchNative])
        .syscalls(syscalls)
        .build()
        .unwrap();
    assert_equivalent(&seccomp);
}

#[test]
fn test_equivalent_conflicting_rules() {
    let native = ScmpArch::Native.resolve_native().unwrap();
    let audit = super::arch::info(native).unwrap().audit;
    let nr = super::arch::resolve(native, "clone3").unwrap();
    let sc = ScmpSyscall::from_name("clone3").unwrap();
    for actions in [
        [ScmpAction::Allow, ScmpAction::Errno(38)],
        [ScmpAction::Errno(38), ScmpAction::Allow],
        [ScmpAction::Errno(1), ScmpAction::Errno(38)],
    ] {
        let rules: Vec<Rule> = actions
            .iter()
            .map(|&action| Rule {
                action,
                syscall: sc,
                comparators: vec![],
            })
            .collect();
        let expected = libseccomp_program(ScmpAction::Trap, &[native], &rules);
        let actual =
            compiler::compile(ScmpAction::Trap, ScmpAction::KillThread, &[native], &rules).unwrap();
        let data = Data {
            nr,
            arch: audit,
            args: [0; 6],
        };
        assert_eq!(run(&actual, &data), run(&expected, &data), "{actions:?}");
        assert_eq!(run(&actual, &data), actions[0].to_ret());
    }
}
