//! A pure Rust subset of the `libseccomp` crate API.
//!
//! This module provides the types and functions of the `libseccomp` crate that
//! are used by youki, so that `crate::seccomp` can switch between the two
//! backends by changing its imports only. The BPF program is generated by
//! [`compiler`] and loaded with the low level primitives of the experimental
//! `seccomp` crate (`experiment/seccomp`).
//!
//! Supported architectures are x86_64, x86, x32, aarch64 and arm.

mod arch;
mod compiler;
mod context;
pub mod error;
mod types;

#[cfg(all(test, feature = "libseccomp"))]
mod difftest;

pub use context::ScmpFilterContext;
pub use types::{ScmpAction, ScmpArch, ScmpArgCompare, ScmpCompareOp, ScmpSyscall};
